---
title: "Analisis Estadístico de la temporada de la NBA 2019"
author:
- Samuel Ruiz
- Scarlet Casique
date: "Abril 2026"
output:
  pdf_document:
    template: template.tex
    keep_tex: true
    toc: true
    number_sections: true
    citation_package: natbib
  html_document:
    toc: true
    df_print: paged
director:
- Jesus Ochoa
- Oliver Triveño
lugar: Caracas
facultad:
- Facultad de Ciencias Económicas y Sociales
- Escuela de Estadistica y Ciencias Actuariales
escudo: Latex/Classes/Escudos/faces
bibliography: bibliografia.bib
degree: Computación I
abstract: |
  En el presente trabajo, se analiza el impacto del factor de localía en la NBA durante la temporada de 2019, utilizando metodos de estadística descriptiva (medidas de tendencia central, medidas de dispersion y correlacion), para determinar si los equipos mejoran su rendimiento, siendo locales, a diferencia de cuando juegan de visitante.  Dicho estudio aportara una buena metodología para el analisis de datos, en general.
---

```{r setup, include=FALSE}
# Configuración global de chunks
knitr::opts_chunk$set(
  echo = FALSE,        # Mostrar código
  warning = FALSE,    # Ocultar advertencias
  message = FALSE,    # Ocultar mensajes de carga
  fig.align = "center",
  out.width = "90%",
  fig.pos = "H",
  out.extra = ""
)

# Cargar librerías necesarias
library(tidyverse)
library(knitr)
library(kableExtra)
library(scales)
library(janitor)
```

\chapter*{Introducción}

En la NBA comunmente reconocen el factor de "localía" y dicho factor lo asocian a una gran frecuencia de victorias en los partidos. No obstante, independientemente del resultado final, existe la interrogante, sobre si éste "factor" o "condición" se puede traducir como una mejora real en el rendimiento estadístico de los equipos.

Por ende, el presente trabajo analiza la temporada 2019 con el objetivo de cuantificar el impacto de la localía, enfocandose en métricas claves (puntos, asistencias, rebotes, etc...). El mismo se realizará, mediante el uso de medidas de tendencia central, medidas de dispersión, diagramas de cajas, y correlaciones. Para determinar si los equipos rinden mejor como locales, si la eficiencia de tiro explica sus victorias siendo locales y tambien, para observar cual estadística se asocia fuertemente con el triunfo estando en dicha "condición".

\chapter{Planteamiento del Problema}

Si bien el fenómeno de la 'ventaja de localía' es un factor reconocido en el baloncesto profesional por su impacto en los resultados finales, persiste una falta de profundidad en el análisis de las variables que lo componen.

Actualmente, no se ha determinado con precisión si esta superioridad se refleja de manera uniforme en las métricas de rendimiento técnico-táctico de los equipos. Por consiguiente, el presente estudio aborda la ausencia de una caracterización estadística detallada que permita cuantificar el impacto real de la localía por equipo y su correlación directa con la eficacia competitiva durante la temporada 2019 de la NBA.

Argumento final. Debido a esto, se plantea las siguientes preguntas de investigación:\

\textbf{1.} ¿Existe una diferencia estadísticamente significativa entre el porcentaje de victorias como "local", de los equipos de la NBA y su eficiencia de tiros de campo (FG_PCT), tiros de tres puntos (FG3_PCT) y tiros libres (FT_PCT) cuando juegan en casa de frente a cuando juegan de visitante durante la temporada de 2019?

\textbf{2.} ¿Los equipos en promedio anotan más puntos, lanzan con mejor porcentaje (en tiros de campo, triples y libres), dan más asistencias y capturan más rebotes, cuando juegan de locales, a diferencia de cuando juegan de visitantes?

\textbf{3.} En base a las estadísticas de los equipos en sus partidos como local (los puntos, las asistencias, y los rebotes) ¿cuál tiene una correlación más alta con la victoria?

\section{Justificación}

Este trabajo se realiza debido a la necesidad de aplicar técnicas de estadística descriptiva junto a herramientas computacionales, para cuantificar, de manera objetiva, el impacto real de la ventaja de la localía en el rendimiento de los equipos de la NBA. Ademas este trabajo ayudaría a entrenadores o aficionados, a identificar cuales aspectos específicos del juego, favorecen más a los equipos, al estar jugando en casa. Cabe mencionar, que este estudio tambien aporta una metodología replicable, haciendo uso de R, para el análisis exploratorio y descriptivo de grandes volúmenes de información.

\section{Objetivos}

\subsection{Objetivo General}
\begin{itemize}
  \item{Analizar el impacto de la localía en el rendimiento estadístico y el resultado final de los equipos de la NBA durante la temporada 2019, comparando los factores de anotación y eficiencia entre partidos de locales y visitantes.}
\end{itemize}
\subsection{Objetivos Específicos}
\begin{enumerate}
  \item Determinar, para cada equipo de la NBA, su porcentaje de victorias como local durante la temporada 2019, y analizar la distribución de las victorias dado el tipo de lanzamiento para evaluar si la ventaja de localia se refleja en el resultado final del marcador por una mayor eficiencia de lanzamiento como local.
  \item Calcular, para cada equipo, la diferencia en su rendimiento promedio como local frente a su rendimiento promedio como visitante en las siguientes estadísticas: puntos anotados, porcentaje de tiros de campo, porcentaje de tiros de tres puntos, porcentaje de tiros libres, asistencias y rebotes totales. Analizar si estas diferencias son, en promedio, favorables a la condición de local.
  \item Analizar la correlación entre las principales estadísticas de rendimiento (puntos, asistencias y rebotes) de los equipos en sus partidos como local y la victoria en dichos partidos, para identificar qué variable presenta una asociación más fuerte con el éxito en condición de local.
\end{enumerate}

\section{Cobertura}

\subsection{Horizontal}

Describir la cobertura Horizontal del trabajo de investigación\

\subsection{Vertical}

La cobertura del trabajo de investigación, toma un total de 1.242 observaciones (o registros) en base al dataset original. Cabe destacar que cada fila representa un partido único en la NBA, y el alcance del dataset, abarca desde la temporada 2013 hasta la 2022, en lo que en el mismo se puede analizar de manera múltiple; solo que en la presente investigación tomaremos la temporada 2019

\section{Periodo de Referencia}

La fuente de los datos proviene del repositorio de (https://www.kaggle.com/datasets). El periodo de referencia competente para el analisis descriptivo, se centrara en la temporada 2019; donde las consistencia de los datos es mejor. Y el procesamiento de la información se realizó con el corte en abril de 2026
\section{Variables}

La variable de "interés" en el estudio es (HOME_TEAM_WINS), la cual representa el éxito competitivo por parte del equipo local

\chapter{Marco Teórico}

\section{Bases Teóricas}

 El presente capitulo expone los fundamentos estadísticos para analizar el rendimiento de los equipos de la NBA durante la temporada 2019. Partiendo de la hipótesis de que la ventaja de jugar como local puede cuantificarse mediante indicadores específicos tales como puntos, porcentajes de tiros, asistencias y rebotes.
 
 Para ello se emplearan herramientas de estadística descriptiva que permiten resumir, visualizar y comparar los datos sin necesidad de formular hipótesis complejas.
 
 Por ende, la comprensión de estos conceptos es fundamental para interpretar, si la localía se traduce en una mejora real del rendimiento.

\subsection{Media Aritenática (Promedio)}

Para una variable cuantitativa cualquiera, por ejemplo: los puntos anotados por un equipo como local (PTS_HOME). sean $x_1, x_2. \ldots, x_n$ correspondientes a cada partido; la media muestral se define como:

$$\bar{x} = \frac{1}{n} \sum_{i=1}^{n} x_i$$ 
  Por lo cual, la media aritmetica compete a los calculos de: porcentajes de victorias como local por temporada, la diferencia de puntos promedio entre locales y visitantes, promedio de asistencia  del local cuando gana vs cuando pierde, promedio de tiros libres por temporada, promedio de puntos totales por partido, para comprar el porcentaje de aciertos en triples entre local y visitantes y para realizar un top 10 de equipos con mayor efectividad como local

\subsection{Desviación estándar}

La desviación estandar mide la dispersión promedio de los datos con respecto a su media; una desviación pequeña indica un rendimiento consistente, dicha desviación se define como : $$ s = \sqrt {\frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^2} $$
 En éste estudio, la desviación estandar se utilizará para calcular sobre los partidos de  la temporada 2019 en cada equipo, específicamente se comprara si los equipos son mas regulares jugando en casa que de visitante  
 
\subsection{Correlación de Pearson}

Para medir la fuerza y dirección de la relación lineal entre dos variables cuantitativas, se utiliza el coeficiente de correlación de pearson $r$, dadas 2 variables $x$ e $y$, se define como: $$ r =  \frac{\sum(x - \bar{x})(y - \bar{y})}{\sqrt{\sum(x - \bar{x})^2 \sum (y - \bar{y})^2}} $$

En este estudio, se calculara la correlación entre las estadísticas de los equipos como local (porcentajes de tiro de campo, porcentajes de tiros libres, porcentaje de triples, asistencias y rebotes) y la variable HOME_TEAM_WINS, para identificar que métrica se asocia mas fuertemente con el éxito en condicion de local
\chapter{Marco Metódico}

En esta sección se presentan las metodologías y/o test necesarios relacionados con la práctica divulgada en el marco teórico, así como las fuentes de datos.

\section{Bases metódicas utilizadas en el trabajo de investigación}

Desarrollo\

\subsection{Item 1}

Descripción\

\subsection{Item 2}

Descripción\

\subsubsection{Item 2.2}

Descripción\

\subsection{Item n}

Descripción\

\chapter{Análisis de Resultados}

{\small Este capítulo presenta los resultados obtenidos al aplicar las metodologías descritas en el capítulo anterior, así como del análisis estadístico descriptivo de las variables estudiadas y las ventajas y desventajas al aplicar dichos tests.}

\section{Presentación de resultados 1}

Descripción\

\section{Presentación de resultados 2}

Descripción\

\section{Presentación de resultados n}

Descripción\

\chapter{Conclusiones y Recomendaciones}

\textbf{1.-} Conclusion 1 del trabajo de investigación.\

\textbf{Recomendación} Recomendación 1 del trabajo de investigación.\

\textbf{2.-} Conclusion 2 del trabajo de investigación.\

\textbf{Recomendación} Recomendación 2 del trabajo de investigación.\

\textbf{n.-} Conclusion n del trabajo de investigación.\

\textbf{Recomendación} Recomendación n del trabajo de investigación.\

\appendix
\renewcommand{\thechapter}{\Alph{chapter}}

\chapter{Anexo A}

\chapter{Anexo B}

\chapter{Anexo C}
